spring.application.name=Teste
spring.datasource.url=jdbc:postgresql://localhost:5432/SEU_BANCO_DE_DADOS
spring.datasource.username=SEU_USUÁRIO
spring.datasource.password=SUA_SENHA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
